# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libmercury', [dirname(__file__)])
        except ImportError:
            import _libmercury
            return _libmercury
        if fp is not None:
            try:
                _mod = imp.load_module('_libmercury', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libmercury = swig_import_helper()
    del swig_import_helper
else:
    import _libmercury
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class SwigPyIterator:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libmercury.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _libmercury.SwigPyIterator_value(self)
    def incr(self, n = 1): return _libmercury.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _libmercury.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _libmercury.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _libmercury.SwigPyIterator_equal(self, *args)
    def copy(self): return _libmercury.SwigPyIterator_copy(self)
    def next(self): return _libmercury.SwigPyIterator_next(self)
    def __next__(self): return _libmercury.SwigPyIterator___next__(self)
    def previous(self): return _libmercury.SwigPyIterator_previous(self)
    def advance(self, *args): return _libmercury.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _libmercury.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _libmercury.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _libmercury.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _libmercury.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _libmercury.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _libmercury.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _libmercury.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _libmercury.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libmercury.IntVector___nonzero__(self)
    def __bool__(self): return _libmercury.IntVector___bool__(self)
    def __len__(self): return _libmercury.IntVector___len__(self)
    def pop(self): return _libmercury.IntVector_pop(self)
    def __getslice__(self, *args): return _libmercury.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _libmercury.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _libmercury.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _libmercury.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _libmercury.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _libmercury.IntVector___setitem__(self, *args)
    def append(self, *args): return _libmercury.IntVector_append(self, *args)
    def empty(self): return _libmercury.IntVector_empty(self)
    def size(self): return _libmercury.IntVector_size(self)
    def clear(self): return _libmercury.IntVector_clear(self)
    def swap(self, *args): return _libmercury.IntVector_swap(self, *args)
    def get_allocator(self): return _libmercury.IntVector_get_allocator(self)
    def begin(self): return _libmercury.IntVector_begin(self)
    def end(self): return _libmercury.IntVector_end(self)
    def rbegin(self): return _libmercury.IntVector_rbegin(self)
    def rend(self): return _libmercury.IntVector_rend(self)
    def pop_back(self): return _libmercury.IntVector_pop_back(self)
    def erase(self, *args): return _libmercury.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _libmercury.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _libmercury.IntVector_push_back(self, *args)
    def front(self): return _libmercury.IntVector_front(self)
    def back(self): return _libmercury.IntVector_back(self)
    def assign(self, *args): return _libmercury.IntVector_assign(self, *args)
    def resize(self, *args): return _libmercury.IntVector_resize(self, *args)
    def insert(self, *args): return _libmercury.IntVector_insert(self, *args)
    def reserve(self, *args): return _libmercury.IntVector_reserve(self, *args)
    def capacity(self): return _libmercury.IntVector_capacity(self)
    __swig_destroy__ = _libmercury.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _libmercury.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _libmercury.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libmercury.DoubleVector___nonzero__(self)
    def __bool__(self): return _libmercury.DoubleVector___bool__(self)
    def __len__(self): return _libmercury.DoubleVector___len__(self)
    def pop(self): return _libmercury.DoubleVector_pop(self)
    def __getslice__(self, *args): return _libmercury.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _libmercury.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _libmercury.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _libmercury.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _libmercury.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _libmercury.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _libmercury.DoubleVector_append(self, *args)
    def empty(self): return _libmercury.DoubleVector_empty(self)
    def size(self): return _libmercury.DoubleVector_size(self)
    def clear(self): return _libmercury.DoubleVector_clear(self)
    def swap(self, *args): return _libmercury.DoubleVector_swap(self, *args)
    def get_allocator(self): return _libmercury.DoubleVector_get_allocator(self)
    def begin(self): return _libmercury.DoubleVector_begin(self)
    def end(self): return _libmercury.DoubleVector_end(self)
    def rbegin(self): return _libmercury.DoubleVector_rbegin(self)
    def rend(self): return _libmercury.DoubleVector_rend(self)
    def pop_back(self): return _libmercury.DoubleVector_pop_back(self)
    def erase(self, *args): return _libmercury.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _libmercury.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _libmercury.DoubleVector_push_back(self, *args)
    def front(self): return _libmercury.DoubleVector_front(self)
    def back(self): return _libmercury.DoubleVector_back(self)
    def assign(self, *args): return _libmercury.DoubleVector_assign(self, *args)
    def resize(self, *args): return _libmercury.DoubleVector_resize(self, *args)
    def insert(self, *args): return _libmercury.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _libmercury.DoubleVector_reserve(self, *args)
    def capacity(self): return _libmercury.DoubleVector_capacity(self)
    __swig_destroy__ = _libmercury.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _libmercury.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class UnsignedIntVector:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnsignedIntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnsignedIntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _libmercury.UnsignedIntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libmercury.UnsignedIntVector___nonzero__(self)
    def __bool__(self): return _libmercury.UnsignedIntVector___bool__(self)
    def __len__(self): return _libmercury.UnsignedIntVector___len__(self)
    def pop(self): return _libmercury.UnsignedIntVector_pop(self)
    def __getslice__(self, *args): return _libmercury.UnsignedIntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _libmercury.UnsignedIntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _libmercury.UnsignedIntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _libmercury.UnsignedIntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _libmercury.UnsignedIntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _libmercury.UnsignedIntVector___setitem__(self, *args)
    def append(self, *args): return _libmercury.UnsignedIntVector_append(self, *args)
    def empty(self): return _libmercury.UnsignedIntVector_empty(self)
    def size(self): return _libmercury.UnsignedIntVector_size(self)
    def clear(self): return _libmercury.UnsignedIntVector_clear(self)
    def swap(self, *args): return _libmercury.UnsignedIntVector_swap(self, *args)
    def get_allocator(self): return _libmercury.UnsignedIntVector_get_allocator(self)
    def begin(self): return _libmercury.UnsignedIntVector_begin(self)
    def end(self): return _libmercury.UnsignedIntVector_end(self)
    def rbegin(self): return _libmercury.UnsignedIntVector_rbegin(self)
    def rend(self): return _libmercury.UnsignedIntVector_rend(self)
    def pop_back(self): return _libmercury.UnsignedIntVector_pop_back(self)
    def erase(self, *args): return _libmercury.UnsignedIntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _libmercury.new_UnsignedIntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _libmercury.UnsignedIntVector_push_back(self, *args)
    def front(self): return _libmercury.UnsignedIntVector_front(self)
    def back(self): return _libmercury.UnsignedIntVector_back(self)
    def assign(self, *args): return _libmercury.UnsignedIntVector_assign(self, *args)
    def resize(self, *args): return _libmercury.UnsignedIntVector_resize(self, *args)
    def insert(self, *args): return _libmercury.UnsignedIntVector_insert(self, *args)
    def reserve(self, *args): return _libmercury.UnsignedIntVector_reserve(self, *args)
    def capacity(self): return _libmercury.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _libmercury.delete_UnsignedIntVector
    __del__ = lambda self : None;
UnsignedIntVector_swigregister = _libmercury.UnsignedIntVector_swigregister
UnsignedIntVector_swigregister(UnsignedIntVector)


def mercury(*args):
  return _libmercury.mercury(*args)
mercury = _libmercury.mercury


