# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\d3p483\workspace\pyXTandem\mainGUI.ui'
#
# Created: Tue Jun 30 15:02:50 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 910)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.minLogEPep_SB = QtGui.QSpinBox(self.tab)
        self.minLogEPep_SB.setMinimum(-1000)
        self.minLogEPep_SB.setMaximum(1000)
        self.minLogEPep_SB.setProperty("value", QtCore.QVariant(-1))
        self.minLogEPep_SB.setObjectName("minLogEPep_SB")
        self.gridLayout.addWidget(self.minLogEPep_SB, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.minLogEProt_SB = QtGui.QSpinBox(self.tab)
        self.minLogEProt_SB.setMinimum(-1000)
        self.minLogEProt_SB.setMaximum(1000)
        self.minLogEProt_SB.setProperty("value", QtCore.QVariant(-1))
        self.minLogEProt_SB.setObjectName("minLogEProt_SB")
        self.gridLayout.addWidget(self.minLogEProt_SB, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.fragErr_SB = QtGui.QDoubleSpinBox(self.tab)
        self.fragErr_SB.setDecimals(4)
        self.fragErr_SB.setMinimum(0.0)
        self.fragErr_SB.setMaximum(1000.0)
        self.fragErr_SB.setProperty("value", QtCore.QVariant(0.4))
        self.fragErr_SB.setObjectName("fragErr_SB")
        self.gridLayout.addWidget(self.fragErr_SB, 5, 1, 1, 1)
        self.fragErr_Type_CB = QtGui.QComboBox(self.tab)
        self.fragErr_Type_CB.setObjectName("fragErr_Type_CB")
        self.fragErr_Type_CB.addItem(QtCore.QString())
        self.fragErr_Type_CB.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.fragErr_Type_CB, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.parentErrPos_SB = QtGui.QDoubleSpinBox(self.tab)
        self.parentErrPos_SB.setDecimals(4)
        self.parentErrPos_SB.setMaximum(10000.0)
        self.parentErrPos_SB.setProperty("value", QtCore.QVariant(100.0))
        self.parentErrPos_SB.setObjectName("parentErrPos_SB")
        self.gridLayout.addWidget(self.parentErrPos_SB, 6, 1, 1, 1)
        self.parentErrType_CB = QtGui.QComboBox(self.tab)
        self.parentErrType_CB.setObjectName("parentErrType_CB")
        self.parentErrType_CB.addItem(QtCore.QString())
        self.parentErrType_CB.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.parentErrType_CB, 6, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.parentErrNeg_SB = QtGui.QDoubleSpinBox(self.tab)
        self.parentErrNeg_SB.setDecimals(4)
        self.parentErrNeg_SB.setMaximum(10000.0)
        self.parentErrNeg_SB.setProperty("value", QtCore.QVariant(100.0))
        self.parentErrNeg_SB.setObjectName("parentErrNeg_SB")
        self.gridLayout.addWidget(self.parentErrNeg_SB, 7, 1, 1, 1)
        self.isotopeErr_CB = QtGui.QCheckBox(self.tab)
        self.isotopeErr_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.isotopeErr_CB.setChecked(True)
        self.isotopeErr_CB.setObjectName("isotopeErr_CB")
        self.gridLayout.addWidget(self.isotopeErr_CB, 10, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 11, 0, 1, 1)
        self.fragType_CB = QtGui.QComboBox(self.tab)
        self.fragType_CB.setObjectName("fragType_CB")
        self.fragType_CB.addItem(QtCore.QString())
        self.fragType_CB.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.fragType_CB, 11, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 12, 0, 1, 1)
        self.removeRedun_CB = QtGui.QCheckBox(self.tab)
        self.removeRedun_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.removeRedun_CB.setObjectName("removeRedun_CB")
        self.gridLayout.addWidget(self.removeRedun_CB, 13, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab)
        self.label_29.setEnabled(False)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 13, 1, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.tab)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setMinimum(0)
        self.spinBox_7.setMaximum(360)
        self.spinBox_7.setProperty("value", QtCore.QVariant(40))
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 13, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 14, 0, 1, 1)
        self.maxCharge_SB = QtGui.QSpinBox(self.tab)
        self.maxCharge_SB.setMinimum(1)
        self.maxCharge_SB.setMaximum(1000)
        self.maxCharge_SB.setObjectName("maxCharge_SB")
        self.gridLayout.addWidget(self.maxCharge_SB, 14, 1, 1, 1)
        self.specSyn_CB = QtGui.QCheckBox(self.tab)
        self.specSyn_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.specSyn_CB.setChecked(True)
        self.specSyn_CB.setObjectName("specSyn_CB")
        self.gridLayout.addWidget(self.specSyn_CB, 15, 0, 1, 1)
        self.noiseSuppress_CB = QtGui.QCheckBox(self.tab)
        self.noiseSuppress_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.noiseSuppress_CB.setObjectName("noiseSuppress_CB")
        self.gridLayout.addWidget(self.noiseSuppress_CB, 16, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 17, 0, 1, 1)
        self.minParent_SB = QtGui.QDoubleSpinBox(self.tab)
        self.minParent_SB.setMaximum(1000000.0)
        self.minParent_SB.setSingleStep(50.0)
        self.minParent_SB.setProperty("value", QtCore.QVariant(400.0))
        self.minParent_SB.setObjectName("minParent_SB")
        self.gridLayout.addWidget(self.minParent_SB, 17, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 18, 0, 1, 1)
        self.minFrag_SB = QtGui.QDoubleSpinBox(self.tab)
        self.minFrag_SB.setMaximum(1000000.0)
        self.minFrag_SB.setSingleStep(50.0)
        self.minFrag_SB.setProperty("value", QtCore.QVariant(150.0))
        self.minFrag_SB.setObjectName("minFrag_SB")
        self.gridLayout.addWidget(self.minFrag_SB, 18, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 19, 0, 1, 1)
        self.totalPeaks_SB = QtGui.QSpinBox(self.tab)
        self.totalPeaks_SB.setMinimum(1)
        self.totalPeaks_SB.setMaximum(100000)
        self.totalPeaks_SB.setProperty("value", QtCore.QVariant(50))
        self.totalPeaks_SB.setObjectName("totalPeaks_SB")
        self.gridLayout.addWidget(self.totalPeaks_SB, 19, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 20, 0, 1, 1)
        self.minPeaks_SB = QtGui.QSpinBox(self.tab)
        self.minPeaks_SB.setMinimum(1)
        self.minPeaks_SB.setMaximum(100000)
        self.minPeaks_SB.setProperty("value", QtCore.QVariant(15))
        self.minPeaks_SB.setObjectName("minPeaks_SB")
        self.gridLayout.addWidget(self.minPeaks_SB, 20, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 21, 0, 1, 1)
        self.useSeqAnno1_CB = QtGui.QCheckBox(self.tab)
        self.useSeqAnno1_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.useSeqAnno1_CB.setChecked(True)
        self.useSeqAnno1_CB.setObjectName("useSeqAnno1_CB")
        self.gridLayout.addWidget(self.useSeqAnno1_CB, 22, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 23, 0, 1, 1)
        self.protNTerm_LE = QtGui.QLineEdit(self.tab)
        self.protNTerm_LE.setObjectName("protNTerm_LE")
        self.gridLayout.addWidget(self.protNTerm_LE, 23, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 24, 0, 1, 1)
        self.protCTerm_LE = QtGui.QLineEdit(self.tab)
        self.protCTerm_LE.setObjectName("protCTerm_LE")
        self.gridLayout.addWidget(self.protCTerm_LE, 24, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 25, 0, 1, 1)
        self.userDefinedMods_LE = QtGui.QLineEdit(self.tab)
        self.userDefinedMods_LE.setObjectName("userDefinedMods_LE")
        self.gridLayout.addWidget(self.userDefinedMods_LE, 25, 1, 1, 1)
        self.numThreads_SB = QtGui.QSpinBox(self.tab)
        self.numThreads_SB.setMinimum(1)
        self.numThreads_SB.setMaximum(1000)
        self.numThreads_SB.setObjectName("numThreads_SB")
        self.gridLayout.addWidget(self.numThreads_SB, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 9, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 10, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 12, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 17, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 11, 0, 1, 1)
        self.refineModel_CB = QtGui.QCheckBox(self.tab)
        self.refineModel_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.refineModel_CB.setChecked(True)
        self.refineModel_CB.setObjectName("refineModel_CB")
        self.gridLayout_2.addWidget(self.refineModel_CB, 1, 0, 1, 1)
        self.useSeqAnno2_CB = QtGui.QCheckBox(self.tab)
        self.useSeqAnno2_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.useSeqAnno2_CB.setChecked(True)
        self.useSeqAnno2_CB.setObjectName("useSeqAnno2_CB")
        self.gridLayout_2.addWidget(self.useSeqAnno2_CB, 2, 0, 1, 1)
        self.pointMut_CB = QtGui.QCheckBox(self.tab)
        self.pointMut_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pointMut_CB.setObjectName("pointMut_CB")
        self.gridLayout_2.addWidget(self.pointMut_CB, 3, 0, 1, 1)
        self.singleAAPoly_CB = QtGui.QCheckBox(self.tab)
        self.singleAAPoly_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.singleAAPoly_CB.setChecked(True)
        self.singleAAPoly_CB.setObjectName("singleAAPoly_CB")
        self.gridLayout_2.addWidget(self.singleAAPoly_CB, 4, 0, 1, 1)
        self.semiCleave1_CB = QtGui.QCheckBox(self.tab)
        self.semiCleave1_CB.setEnabled(False)
        self.semiCleave1_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.semiCleave1_CB.setObjectName("semiCleave1_CB")
        self.gridLayout_2.addWidget(self.semiCleave1_CB, 5, 0, 1, 1)
        self.useModsThroughout_CB = QtGui.QCheckBox(self.tab)
        self.useModsThroughout_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.useModsThroughout_CB.setObjectName("useModsThroughout_CB")
        self.gridLayout_2.addWidget(self.useModsThroughout_CB, 6, 0, 1, 1)
        self.unanticipatedCleave_CB = QtGui.QCheckBox(self.tab)
        self.unanticipatedCleave_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.unanticipatedCleave_CB.setChecked(True)
        self.unanticipatedCleave_CB.setObjectName("unanticipatedCleave_CB")
        self.gridLayout_2.addWidget(self.unanticipatedCleave_CB, 7, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 0, 0, 1, 1)
        self.semiCleave_CB = QtGui.QCheckBox(self.tab)
        self.semiCleave_CB.setEnabled(False)
        self.semiCleave_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.semiCleave_CB.setObjectName("semiCleave_CB")
        self.gridLayout_2.addWidget(self.semiCleave_CB, 16, 0, 1, 1)
        self.potenNTermMods_LE = QtGui.QLineEdit(self.tab)
        self.potenNTermMods_LE.setObjectName("potenNTermMods_LE")
        self.gridLayout_2.addWidget(self.potenNTermMods_LE, 9, 1, 1, 1)
        self.potenCTermMods_LE = QtGui.QLineEdit(self.tab)
        self.potenCTermMods_LE.setObjectName("potenCTermMods_LE")
        self.gridLayout_2.addWidget(self.potenCTermMods_LE, 8, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 14, 0, 1, 1)
        self.customCleaveRule_LE = QtGui.QLineEdit(self.tab)
        self.customCleaveRule_LE.setObjectName("customCleaveRule_LE")
        self.gridLayout_2.addWidget(self.customCleaveRule_LE, 14, 1, 1, 1)
        self.maxMissedCleaves_SB = QtGui.QSpinBox(self.tab)
        self.maxMissedCleaves_SB.setMaximum(10000)
        self.maxMissedCleaves_SB.setProperty("value", QtCore.QVariant(1))
        self.maxMissedCleaves_SB.setObjectName("maxMissedCleaves_SB")
        self.gridLayout_2.addWidget(self.maxMissedCleaves_SB, 17, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 18, 0, 1, 1)
        self.cleaveNTermChange_label = QtGui.QLabel(self.tab)
        self.cleaveNTermChange_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cleaveNTermChange_label.setObjectName("cleaveNTermChange_label")
        self.gridLayout_2.addWidget(self.cleaveNTermChange_label, 19, 0, 1, 1)
        self.refineEVal_SB = QtGui.QDoubleSpinBox(self.tab)
        self.refineEVal_SB.setDecimals(4)
        self.refineEVal_SB.setMinimum(-1000.0)
        self.refineEVal_SB.setMaximum(100.0)
        self.refineEVal_SB.setProperty("value", QtCore.QVariant(-2.0))
        self.refineEVal_SB.setObjectName("refineEVal_SB")
        self.gridLayout_2.addWidget(self.refineEVal_SB, 10, 1, 1, 1)
        self.cleaveNTermChange_SB = QtGui.QDoubleSpinBox(self.tab)
        self.cleaveNTermChange_SB.setDecimals(6)
        self.cleaveNTermChange_SB.setProperty("value", QtCore.QVariant(1.0))
        self.cleaveNTermChange_SB.setObjectName("cleaveNTermChange_SB")
        self.gridLayout_2.addWidget(self.cleaveNTermChange_SB, 19, 1, 1, 1)
        self.cleaveCTermChange_SB = QtGui.QDoubleSpinBox(self.tab)
        self.cleaveCTermChange_SB.setDecimals(6)
        self.cleaveCTermChange_SB.setMaximum(1000000.0)
        self.cleaveCTermChange_SB.setProperty("value", QtCore.QVariant(17.0))
        self.cleaveCTermChange_SB.setObjectName("cleaveCTermChange_SB")
        self.gridLayout_2.addWidget(self.cleaveCTermChange_SB, 18, 1, 1, 1)
        self.cleaveSite_CB = QtGui.QComboBox(self.tab)
        self.cleaveSite_CB.setObjectName("cleaveSite_CB")
        self.gridLayout_2.addWidget(self.cleaveSite_CB, 12, 1, 1, 1)
        self.cleaveRule_LE = QtGui.QLineEdit(self.tab)
        self.cleaveRule_LE.setReadOnly(True)
        self.cleaveRule_LE.setObjectName("cleaveRule_LE")
        self.gridLayout_2.addWidget(self.cleaveRule_LE, 13, 1, 1, 1)
        self.aaMod_LE = QtGui.QLineEdit(self.tab)
        self.aaMod_LE.setObjectName("aaMod_LE")
        self.gridLayout_2.addWidget(self.aaMod_LE, 15, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 15, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 2, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.fragTypeListWidget = QtGui.QListWidget(self.tab)
        self.fragTypeListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.fragTypeListWidget.setObjectName("fragTypeListWidget")
        self.verticalLayout_2.addWidget(self.fragTypeListWidget)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.taxonListWidget = QtGui.QListWidget(self.tab)
        self.taxonListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.taxonListWidget.setObjectName("taxonListWidget")
        self.verticalLayout.addWidget(self.taxonListWidget)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xtInputFile_Btn = QtGui.QPushButton(self.tab)
        self.xtInputFile_Btn.setObjectName("xtInputFile_Btn")
        self.horizontalLayout_3.addWidget(self.xtInputFile_Btn)
        self.inputFile_LE = QtGui.QLineEdit(self.tab)
        self.inputFile_LE.setObjectName("inputFile_LE")
        self.horizontalLayout_3.addWidget(self.inputFile_LE)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.rawData_Btn = QtGui.QPushButton(self.tab)
        self.rawData_Btn.setObjectName("rawData_Btn")
        self.horizontalLayout_3.addWidget(self.rawData_Btn)
        self.rawData_LE = QtGui.QLineEdit(self.tab)
        self.rawData_LE.setObjectName("rawData_LE")
        self.horizontalLayout_3.addWidget(self.rawData_LE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.xtOutputFile_Btn = QtGui.QPushButton(self.tab)
        self.xtOutputFile_Btn.setObjectName("xtOutputFile_Btn")
        self.horizontalLayout_5.addWidget(self.xtOutputFile_Btn)
        self.outputFile_LE = QtGui.QLineEdit(self.tab)
        self.outputFile_LE.setObjectName("outputFile_LE")
        self.horizontalLayout_5.addWidget(self.outputFile_LE)
        self.outputAll_CB = QtGui.QCheckBox(self.tab)
        self.outputAll_CB.setObjectName("outputAll_CB")
        self.horizontalLayout_5.addWidget(self.outputAll_CB)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.makeXT_Output_Btn = QtGui.QPushButton(self.tab)
        self.makeXT_Output_Btn.setObjectName("makeXT_Output_Btn")
        self.horizontalLayout.addWidget(self.makeXT_Output_Btn)
        self.runXT_Btn = QtGui.QPushButton(self.tab)
        self.runXT_Btn.setObjectName("runXT_Btn")
        self.horizontalLayout.addWidget(self.runXT_Btn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.output_TE = QtGui.QTextEdit(self.tab)
        self.output_TE.setReadOnly(True)
        self.output_TE.setObjectName("output_TE")
        self.verticalLayout_3.addWidget(self.output_TE)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self._2 = QtGui.QGridLayout()
        self._2.setObjectName("_2")
        self._3 = QtGui.QVBoxLayout()
        self._3.setObjectName("_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.defaultXTEXE_Btn = QtGui.QPushButton(self.tab_2)
        self.defaultXTEXE_Btn.setEnabled(True)
        self.defaultXTEXE_Btn.setObjectName("defaultXTEXE_Btn")
        self.horizontalLayout_4.addWidget(self.defaultXTEXE_Btn)
        self.defaultXTEXE_LE = QtGui.QLineEdit(self.tab_2)
        self.defaultXTEXE_LE.setReadOnly(True)
        self.defaultXTEXE_LE.setObjectName("defaultXTEXE_LE")
        self.horizontalLayout_4.addWidget(self.defaultXTEXE_LE)
        self._3.addLayout(self.horizontalLayout_4)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName("_4")
        self.defaultFolder_Btn = QtGui.QPushButton(self.tab_2)
        self.defaultFolder_Btn.setEnabled(True)
        self.defaultFolder_Btn.setObjectName("defaultFolder_Btn")
        self._4.addWidget(self.defaultFolder_Btn)
        self.defaultFolder_LE = QtGui.QLineEdit(self.tab_2)
        self.defaultFolder_LE.setReadOnly(True)
        self.defaultFolder_LE.setObjectName("defaultFolder_LE")
        self._4.addWidget(self.defaultFolder_LE)
        self._3.addLayout(self._4)
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName("_5")
        self.savePref_Btn = QtGui.QPushButton(self.tab_2)
        self.savePref_Btn.setObjectName("savePref_Btn")
        self._5.addWidget(self.savePref_Btn)
        self.revert_Btn = QtGui.QPushButton(self.tab_2)
        self.revert_Btn.setObjectName("revert_Btn")
        self._5.addWidget(self.revert_Btn)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._5.addItem(spacerItem4)
        self._3.addLayout(self._5)
        self._2.addLayout(self._3, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem5, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._2.addItem(spacerItem6, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.defaultTaxFile_Btn = QtGui.QPushButton(self.tab_2)
        self.defaultTaxFile_Btn.setEnabled(True)
        self.defaultTaxFile_Btn.setObjectName("defaultTaxFile_Btn")
        self.horizontalLayout_2.addWidget(self.defaultTaxFile_Btn)
        self.defaultTaxFile_LE = QtGui.QLineEdit(self.tab_2)
        self.defaultTaxFile_LE.setReadOnly(True)
        self.defaultTaxFile_LE.setObjectName("defaultTaxFile_LE")
        self.horizontalLayout_2.addWidget(self.defaultTaxFile_LE)
        self._2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self._2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyX!Tandem", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Minimum log(e) value for peptides:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Minimum log(e) value for proteins:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Measurement Errors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Fragment Mass Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.fragErr_Type_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "Daltons", None, QtGui.QApplication.UnicodeUTF8))
        self.fragErr_Type_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "ppm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Parent Mass Error (+):", None, QtGui.QApplication.UnicodeUTF8))
        self.parentErrType_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "ppm", None, QtGui.QApplication.UnicodeUTF8))
        self.parentErrType_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "Daltons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Parent Mass Error (-):", None, QtGui.QApplication.UnicodeUTF8))
        self.isotopeErr_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Use Isotope Error", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Fragment Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.fragType_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "monoisotopic", None, QtGui.QApplication.UnicodeUTF8))
        self.fragType_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Signal Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRedun_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Remove Redundant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Maximum Parent Charge:", None, QtGui.QApplication.UnicodeUTF8))
        self.specSyn_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Spectrum Synthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.noiseSuppress_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Noise Suppression", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Minimum parent (M+H):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Minimum fragment m/z?:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Total Peaks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Minimum Peaks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Protein Modification", None, QtGui.QApplication.UnicodeUTF8))
        self.useSeqAnno1_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Use Sequence Annotations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Protein N-terminus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Protein C-terminus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "User Defined Potential Modifications:", None, QtGui.QApplication.UnicodeUTF8))
        self.userDefinedMods_LE.setToolTip(QtGui.QApplication.translate("MainWindow", "The format of this parameter is similar to residue, modification mass, with the addition of a modified PROSITE notation sequence motif specification.  For example, a value of 80@[ST!]PX[KR] indicates a modification of either S or T when followed by P, and residue and the a K or an R. A value of 204@N!{P}[ST]{P} indicates a modification of N by 204, if it         is NOT followed by a P, then either an S or a T, NOT followed by a P.  Positive and negative values are allowed.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Number of Threads:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Potential C-terminus mods:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Potential N-terminus mods:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Maximum expectation value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Enzymatic Cleavage Site:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Missed Cleavages allowed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Protein Cleavage", None, QtGui.QApplication.UnicodeUTF8))
        self.refineModel_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Refine Model", None, QtGui.QApplication.UnicodeUTF8))
        self.useSeqAnno2_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Use Sequence Annotations", None, QtGui.QApplication.UnicodeUTF8))
        self.pointMut_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Point Mutations", None, QtGui.QApplication.UnicodeUTF8))
        self.singleAAPoly_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Single amino acid polymorphisms", None, QtGui.QApplication.UnicodeUTF8))
        self.semiCleave1_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Semi-cleavage", None, QtGui.QApplication.UnicodeUTF8))
        self.useModsThroughout_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Use Mods Throughout", None, QtGui.QApplication.UnicodeUTF8))
        self.unanticipatedCleave_CB.setText(QtGui.QApplication.translate("MainWindow", ":?([Unanticipated Cleavages ([X]|[X ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Refinement Specifications", None, QtGui.QApplication.UnicodeUTF8))
        self.semiCleave_CB.setText(QtGui.QApplication.translate("MainWindow", ":?Semi-cleavage", None, QtGui.QApplication.UnicodeUTF8))
        self.potenNTermMods_LE.setText(QtGui.QApplication.translate("MainWindow", "+42.010565@[", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Custom Cleavage Rule:", None, QtGui.QApplication.UnicodeUTF8))
        self.customCleaveRule_LE.setToolTip(QtGui.QApplication.translate("MainWindow", "[RK]|{P} corresponds to the enzyme trypsin. The first charactersin brackets represent residues N-terminal to the bond - the \'|\' pipe - and the second set of characters represent residues C-terminal to thebond. The characters must be in square brackets (denoting that only these residues are allowed for a cleavage) or french brackets (denoting that these residues cannot be in that position). Use UPPERCASE characters.  To denote cleavage at any residue, use [X]|[X] and reset the scoring, maximum missed cleavage site parameter (see below) to something like 50.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Cleavage C-terminal change (Da):", None, QtGui.QApplication.UnicodeUTF8))
        self.cleaveNTermChange_label.setText(QtGui.QApplication.translate("MainWindow", "Cleavage N-terminal change (Da):", None, QtGui.QApplication.UnicodeUTF8))
        self.aaMod_LE.setToolTip(QtGui.QApplication.translate("MainWindow", "The format of this parameter is m@X, where m is the modfication mass in Daltons and X is the appropriate residue to modify. Lists of modifications are separated by commas. For example, to modify M and C with the addition of 16.0 Daltons, the parameter line would be\n"
"+16.0@M,+16.0@C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Amino Acid Modification:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Fragment Types:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Taxon:", None, QtGui.QApplication.UnicodeUTF8))
        self.xtInputFile_Btn.setText(QtGui.QApplication.translate("MainWindow", "X!Tandem Input File:", None, QtGui.QApplication.UnicodeUTF8))
        self.rawData_Btn.setToolTip(QtGui.QApplication.translate("MainWindow", "Usually an mgf or mzXML file.", None, QtGui.QApplication.UnicodeUTF8))
        self.rawData_Btn.setText(QtGui.QApplication.translate("MainWindow", "Raw Data Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.xtOutputFile_Btn.setText(QtGui.QApplication.translate("MainWindow", "X!Tandem Output File:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputAll_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "If this is unchecked only the valid (i.e. not stochastic) will be output.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputAll_CB.setText(QtGui.QApplication.translate("MainWindow", "Output all hits?", None, QtGui.QApplication.UnicodeUTF8))
        self.makeXT_Output_Btn.setText(QtGui.QApplication.translate("MainWindow", "Create X!Tandem Input", None, QtGui.QApplication.UnicodeUTF8))
        self.runXT_Btn.setText(QtGui.QApplication.translate("MainWindow", "Run X!Tandem", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "X!Tandem", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultXTEXE_Btn.setText(QtGui.QApplication.translate("MainWindow", "Default X!Tandem Executable:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultFolder_Btn.setText(QtGui.QApplication.translate("MainWindow", "Default Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.savePref_Btn.setText(QtGui.QApplication.translate("MainWindow", "Save Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.revert_Btn.setText(QtGui.QApplication.translate("MainWindow", "Revert to Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultTaxFile_Btn.setText(QtGui.QApplication.translate("MainWindow", "Default Taxonomy File:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))

