# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\d3p483\workspace\SimpleView\main.ui'
#
# Created: Mon Oct 12 10:38:53 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 765)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/Retro Mario World_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridlayout = QtGui.QGridLayout(self.centralwidget)
        self.gridlayout.setObjectName("gridlayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.gridlayout1 = QtGui.QGridLayout(self.plotTab)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_2 = QtGui.QLabel(self.plotTab)
        self.label_2.setObjectName("label_2")
        self.hboxlayout1.addWidget(self.label_2)
        self.specNameEdit = QtGui.QLineEdit(self.plotTab)
        self.specNameEdit.setReadOnly(True)
        self.specNameEdit.setObjectName("specNameEdit")
        self.hboxlayout1.addWidget(self.specNameEdit)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.plotWidget = MPL_Widget(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.vboxlayout.addWidget(self.plotWidget)
        self.hboxlayout.addLayout(self.vboxlayout)
        self.tabWidget_2 = QtGui.QTabWidget(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridlayout2 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout2.setObjectName("gridlayout2")
        self.groupTreeWidget = QtGui.QTreeWidget(self.tab_4)
        self.groupTreeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.groupTreeWidget.setHeaderHidden(False)
        self.groupTreeWidget.setColumnCount(1)
        self.groupTreeWidget.setObjectName("groupTreeWidget")
        self.gridlayout2.addWidget(self.groupTreeWidget, 0, 0, 1, 1)
        self.multiPlot_CB = QtGui.QCheckBox(self.tab_4)
        self.multiPlot_CB.setObjectName("multiPlot_CB")
        self.gridlayout2.addWidget(self.multiPlot_CB, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabPeakTable = CustomTable(self.tab_5)
        self.tabPeakTable.setObjectName("tabPeakTable")
        self.tabPeakTable.setColumnCount(0)
        self.tabPeakTable.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tabPeakTable)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.zoomPercent_CB = QtGui.QComboBox(self.tab_5)
        self.zoomPercent_CB.setObjectName("zoomPercent_CB")
        self.zoomPercent_CB.addItem(QtCore.QString())
        self.zoomPercent_CB.addItem(QtCore.QString())
        self.zoomPercent_CB.addItem(QtCore.QString())
        self.zoomPercent_CB.addItem(QtCore.QString())
        self.zoomPercent_CB.addItem(QtCore.QString())
        self.horizontalLayout_4.addWidget(self.zoomPercent_CB)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.hboxlayout.addWidget(self.tabWidget_2)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setHorizontalSpacing(3)
        self.gridlayout3.setVerticalSpacing(2)
        self.gridlayout3.setObjectName("gridlayout3")
        self.cALabelLE = QtGui.QLineEdit(self.plotTab)
        self.cALabelLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cALabelLE.setFont(font)
        self.cALabelLE.setReadOnly(True)
        self.cALabelLE.setObjectName("cALabelLE")
        self.gridlayout3.addWidget(self.cALabelLE, 0, 3, 1, 1)
        self.cAIndexLE = QtGui.QLineEdit(self.plotTab)
        self.cAIndexLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cAIndexLE.setFont(font)
        self.cAIndexLE.setReadOnly(True)
        self.cAIndexLE.setObjectName("cAIndexLE")
        self.gridlayout3.addWidget(self.cAIndexLE, 0, 5, 1, 1)
        self.cA_XLE = QtGui.QLineEdit(self.plotTab)
        self.cA_XLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cA_XLE.setFont(font)
        self.cA_XLE.setReadOnly(True)
        self.cA_XLE.setObjectName("cA_XLE")
        self.gridlayout3.addWidget(self.cA_XLE, 0, 7, 1, 1)
        self.cA_YLE = QtGui.QLineEdit(self.plotTab)
        self.cA_YLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cA_YLE.setFont(font)
        self.cA_YLE.setReadOnly(True)
        self.cA_YLE.setObjectName("cA_YLE")
        self.gridlayout3.addWidget(self.cA_YLE, 0, 9, 1, 1)
        self.cBLabelLE = QtGui.QLineEdit(self.plotTab)
        self.cBLabelLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cBLabelLE.setFont(font)
        self.cBLabelLE.setReadOnly(True)
        self.cBLabelLE.setObjectName("cBLabelLE")
        self.gridlayout3.addWidget(self.cBLabelLE, 1, 3, 1, 1)
        self.cBIndexLE = QtGui.QLineEdit(self.plotTab)
        self.cBIndexLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cBIndexLE.setFont(font)
        self.cBIndexLE.setReadOnly(True)
        self.cBIndexLE.setObjectName("cBIndexLE")
        self.gridlayout3.addWidget(self.cBIndexLE, 1, 5, 1, 1)
        self.cB_XLE = QtGui.QLineEdit(self.plotTab)
        self.cB_XLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cB_XLE.setFont(font)
        self.cB_XLE.setReadOnly(True)
        self.cB_XLE.setObjectName("cB_XLE")
        self.gridlayout3.addWidget(self.cB_XLE, 1, 7, 1, 1)
        self.cB_YLE = QtGui.QLineEdit(self.plotTab)
        self.cB_YLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cB_YLE.setFont(font)
        self.cB_YLE.setReadOnly(True)
        self.cB_YLE.setObjectName("cB_YLE")
        self.gridlayout3.addWidget(self.cB_YLE, 1, 9, 1, 1)
        self.label_3 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridlayout3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridlayout3.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridlayout3.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridlayout3.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridlayout3.addWidget(self.label_7, 0, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridlayout3.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridlayout3.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_10 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridlayout3.addWidget(self.label_10, 1, 8, 1, 1)
        self.label_11 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridlayout3.addWidget(self.label_11, 0, 10, 1, 1)
        self.label_12 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridlayout3.addWidget(self.label_12, 1, 10, 1, 1)
        self.dxLE = QtGui.QLineEdit(self.plotTab)
        self.dxLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.dxLE.setFont(font)
        self.dxLE.setReadOnly(True)
        self.dxLE.setObjectName("dxLE")
        self.gridlayout3.addWidget(self.dxLE, 0, 11, 1, 1)
        self.dyLE = QtGui.QLineEdit(self.plotTab)
        self.dyLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.dyLE.setFont(font)
        self.dyLE.setReadOnly(True)
        self.dyLE.setObjectName("dyLE")
        self.gridlayout3.addWidget(self.dyLE, 1, 11, 1, 1)
        self.cursACB = QtGui.QCheckBox(self.plotTab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.cursACB.setFont(font)
        self.cursACB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cursACB.setObjectName("cursACB")
        self.gridlayout3.addWidget(self.cursACB, 0, 0, 1, 1)
        self.cursBCB = QtGui.QCheckBox(self.plotTab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.cursBCB.setFont(font)
        self.cursBCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cursBCB.setObjectName("cursBCB")
        self.gridlayout3.addWidget(self.cursBCB, 1, 0, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.plotTab, "")
        self.optionsTab = QtGui.QWidget()
        self.optionsTab.setObjectName("optionsTab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.optionsTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.loadmzXMLCB = QtGui.QCheckBox(self.optionsTab)
        self.loadmzXMLCB.setChecked(True)
        self.loadmzXMLCB.setObjectName("loadmzXMLCB")
        self.gridLayout.addWidget(self.loadmzXMLCB, 0, 0, 1, 1)
        self.plotLegendCB = QtGui.QCheckBox(self.optionsTab)
        self.plotLegendCB.setChecked(True)
        self.plotLegendCB.setObjectName("plotLegendCB")
        self.gridLayout.addWidget(self.plotLegendCB, 0, 1, 1, 1)
        self.plotPkListCB = QtGui.QCheckBox(self.optionsTab)
        self.plotPkListCB.setChecked(True)
        self.plotPkListCB.setObjectName("plotPkListCB")
        self.gridLayout.addWidget(self.plotPkListCB, 0, 2, 1, 1)
        self.autoSavePkList_CB = QtGui.QCheckBox(self.optionsTab)
        self.autoSavePkList_CB.setChecked(True)
        self.autoSavePkList_CB.setObjectName("autoSavePkList_CB")
        self.gridLayout.addWidget(self.autoSavePkList_CB, 0, 3, 1, 1)
        self.excludeLIFTCB = QtGui.QCheckBox(self.optionsTab)
        self.excludeLIFTCB.setObjectName("excludeLIFTCB")
        self.gridLayout.addWidget(self.excludeLIFTCB, 1, 0, 1, 1)
        self.labelPeak_CB = QtGui.QCheckBox(self.optionsTab)
        self.labelPeak_CB.setChecked(False)
        self.labelPeak_CB.setObjectName("labelPeak_CB")
        self.gridLayout.addWidget(self.labelPeak_CB, 1, 1, 1, 1)
        self.plotNoiseEst_CB = QtGui.QCheckBox(self.optionsTab)
        self.plotNoiseEst_CB.setChecked(False)
        self.plotNoiseEst_CB.setObjectName("plotNoiseEst_CB")
        self.gridLayout.addWidget(self.plotNoiseEst_CB, 1, 2, 1, 1)
        self.invertCompCB = QtGui.QCheckBox(self.optionsTab)
        self.invertCompCB.setChecked(True)
        self.invertCompCB.setObjectName("invertCompCB")
        self.gridLayout.addWidget(self.invertCompCB, 1, 3, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_18 = QtGui.QLabel(self.optionsTab)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.hboxlayout2.addWidget(self.label_18)
        self.globalPPM_SB = QtGui.QDoubleSpinBox(self.optionsTab)
        self.globalPPM_SB.setMinimum(0.01)
        self.globalPPM_SB.setMaximum(50000.0)
        self.globalPPM_SB.setSingleStep(10.0)
        self.globalPPM_SB.setProperty("value", QtCore.QVariant(500.0))
        self.globalPPM_SB.setObjectName("globalPPM_SB")
        self.hboxlayout2.addWidget(self.globalPPM_SB)
        self.gridLayout.addLayout(self.hboxlayout2, 2, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_13 = QtGui.QLabel(self.optionsTab)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.hboxlayout3.addWidget(self.label_13)
        self.mzLo_SB = QtGui.QDoubleSpinBox(self.optionsTab)
        self.mzLo_SB.setDecimals(3)
        self.mzLo_SB.setMinimum(1.0)
        self.mzLo_SB.setMaximum(100000.0)
        self.mzLo_SB.setSingleStep(0.05)
        self.mzLo_SB.setProperty("value", QtCore.QVariant(1295.0))
        self.mzLo_SB.setObjectName("mzLo_SB")
        self.hboxlayout3.addWidget(self.mzLo_SB)
        self.vboxlayout1.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label_14 = QtGui.QLabel(self.optionsTab)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.hboxlayout4.addWidget(self.label_14)
        self.mzHi_SB = QtGui.QDoubleSpinBox(self.optionsTab)
        self.mzHi_SB.setDecimals(3)
        self.mzHi_SB.setMinimum(-1.0)
        self.mzHi_SB.setMaximum(100000.0)
        self.mzHi_SB.setSingleStep(0.05)
        self.mzHi_SB.setProperty("value", QtCore.QVariant(1297.0))
        self.mzHi_SB.setObjectName("mzHi_SB")
        self.hboxlayout4.addWidget(self.mzHi_SB)
        self.vboxlayout1.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.getEIC_Btn = QtGui.QPushButton(self.optionsTab)
        self.getEIC_Btn.setObjectName("getEIC_Btn")
        self.hboxlayout5.addWidget(self.getEIC_Btn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout5)
        self.horizontalLayout_3.addLayout(self.vboxlayout1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.frame = QtGui.QFrame(self.optionsTab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName("_2")
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self._2.addWidget(self.label_20)
        self.peakPick_CB = QtGui.QComboBox(self.frame)
        self.peakPick_CB.setObjectName("peakPick_CB")
        self.peakPick_CB.addItem(QtCore.QString())
        self.peakPick_CB.addItem(QtCore.QString())
        self.peakPick_CB.addItem(QtCore.QString())
        self._2.addWidget(self.peakPick_CB)
        self.verticalLayout.addLayout(self._2)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.hboxlayout6.addWidget(self.label_16)
        self.snrNoiseEst_SB = QtGui.QDoubleSpinBox(self.frame)
        self.snrNoiseEst_SB.setDecimals(1)
        self.snrNoiseEst_SB.setMinimum(1.0)
        self.snrNoiseEst_SB.setMaximum(5000.0)
        self.snrNoiseEst_SB.setProperty("value", QtCore.QVariant(3.0))
        self.snrNoiseEst_SB.setObjectName("snrNoiseEst_SB")
        self.hboxlayout6.addWidget(self.snrNoiseEst_SB)
        self.verticalLayout.addLayout(self.hboxlayout6)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.hboxlayout7.addWidget(self.label_17)
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.hboxlayout7.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.hboxlayout7)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.tabWidget_PP = QtGui.QTabWidget(self.frame)
        self.tabWidget_PP.setObjectName("tabWidget_PP")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setMaximum(1000000.0)
        self.doubleSpinBox.setSingleStep(50.0)
        self.doubleSpinBox.setProperty("value", QtCore.QVariant(10000.0))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_6.addWidget(self.label_32)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.05)
        self.doubleSpinBox_2.setProperty("value", QtCore.QVariant(0.03))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_33 = QtGui.QLabel(self.tab)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_7.addWidget(self.label_33)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.tabWidget_PP.addTab(self.tab, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.hboxlayout8.addWidget(self.label_25)
        self.peakSetting_CB = QtGui.QComboBox(self.tab_6)
        self.peakSetting_CB.setObjectName("peakSetting_CB")
        self.hboxlayout8.addWidget(self.peakSetting_CB)
        self.verticalLayout_2.addLayout(self.hboxlayout8)
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.label_21 = QtGui.QLabel(self.tab_6)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.hboxlayout9.addWidget(self.label_21)
        self.minRow_SB = QtGui.QSpinBox(self.tab_6)
        self.minRow_SB.setMinimum(1)
        self.minRow_SB.setMaximum(100)
        self.minRow_SB.setProperty("value", QtCore.QVariant(1))
        self.minRow_SB.setObjectName("minRow_SB")
        self.hboxlayout9.addWidget(self.minRow_SB)
        self.verticalLayout_2.addLayout(self.hboxlayout9)
        self.hboxlayout10 = QtGui.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.label_22 = QtGui.QLabel(self.tab_6)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.hboxlayout10.addWidget(self.label_22)
        self.minClust_SB = QtGui.QSpinBox(self.tab_6)
        self.minClust_SB.setMinimum(1)
        self.minClust_SB.setMaximum(100)
        self.minClust_SB.setProperty("value", QtCore.QVariant(4))
        self.minClust_SB.setObjectName("minClust_SB")
        self.hboxlayout10.addWidget(self.minClust_SB)
        self.verticalLayout_2.addLayout(self.hboxlayout10)
        self.hboxlayout11 = QtGui.QHBoxLayout()
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.label_19 = QtGui.QLabel(self.tab_6)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.hboxlayout11.addWidget(self.label_19)
        self.waveletRowTol_SB = QtGui.QSpinBox(self.tab_6)
        self.waveletRowTol_SB.setMinimum(1)
        self.waveletRowTol_SB.setProperty("value", QtCore.QVariant(3))
        self.waveletRowTol_SB.setObjectName("waveletRowTol_SB")
        self.hboxlayout11.addWidget(self.waveletRowTol_SB)
        self.verticalLayout_2.addLayout(self.hboxlayout11)
        self.hboxlayout12 = QtGui.QHBoxLayout()
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.hboxlayout12.addWidget(self.label_23)
        self.dbscanEPS_SB = QtGui.QSpinBox(self.tab_6)
        self.dbscanEPS_SB.setMinimum(-1)
        self.dbscanEPS_SB.setMaximum(1000)
        self.dbscanEPS_SB.setProperty("value", QtCore.QVariant(-1))
        self.dbscanEPS_SB.setObjectName("dbscanEPS_SB")
        self.hboxlayout12.addWidget(self.dbscanEPS_SB)
        self.verticalLayout_2.addLayout(self.hboxlayout12)
        self.hboxlayout13 = QtGui.QHBoxLayout()
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.label_15 = QtGui.QLabel(self.tab_6)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.hboxlayout13.addWidget(self.label_15)
        self.noiseFactor_SB = QtGui.QSpinBox(self.tab_6)
        self.noiseFactor_SB.setMinimum(1)
        self.noiseFactor_SB.setMaximum(100)
        self.noiseFactor_SB.setProperty("value", QtCore.QVariant(10))
        self.noiseFactor_SB.setObjectName("noiseFactor_SB")
        self.hboxlayout13.addWidget(self.noiseFactor_SB)
        self.verticalLayout_2.addLayout(self.hboxlayout13)
        self.hboxlayout14 = QtGui.QHBoxLayout()
        self.hboxlayout14.setObjectName("hboxlayout14")
        self.label_24 = QtGui.QLabel(self.tab_6)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.hboxlayout14.addWidget(self.label_24)
        self.staticCutoff_SB = QtGui.QSpinBox(self.tab_6)
        self.staticCutoff_SB.setMaximum(1000000)
        self.staticCutoff_SB.setProperty("value", QtCore.QVariant(100))
        self.staticCutoff_SB.setObjectName("staticCutoff_SB")
        self.hboxlayout14.addWidget(self.staticCutoff_SB)
        self.verticalLayout_2.addLayout(self.hboxlayout14)
        self.showCWT_CB = QtGui.QCheckBox(self.tab_6)
        self.showCWT_CB.setObjectName("showCWT_CB")
        self.verticalLayout_2.addWidget(self.showCWT_CB)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget_PP.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName("_5")
        self.label_27 = QtGui.QLabel(self.tab_7)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self._5.addWidget(self.label_27)
        self.lowResMinSNR_SB = QtGui.QSpinBox(self.tab_7)
        self.lowResMinSNR_SB.setMinimum(2)
        self.lowResMinSNR_SB.setMaximum(250000)
        self.lowResMinSNR_SB.setProperty("value", QtCore.QVariant(5))
        self.lowResMinSNR_SB.setObjectName("lowResMinSNR_SB")
        self._5.addWidget(self.lowResMinSNR_SB)
        self.verticalLayout_3.addLayout(self._5)
        self._6 = QtGui.QHBoxLayout()
        self._6.setObjectName("_6")
        self.label_28 = QtGui.QLabel(self.tab_7)
        self.label_28.setEnabled(False)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self._6.addWidget(self.label_28)
        self.slopeThreshSB = QtGui.QDoubleSpinBox(self.tab_7)
        self.slopeThreshSB.setEnabled(False)
        self.slopeThreshSB.setObjectName("slopeThreshSB")
        self._6.addWidget(self.slopeThreshSB)
        self.verticalLayout_3.addLayout(self._6)
        self._7 = QtGui.QHBoxLayout()
        self._7.setObjectName("_7")
        self.label_29 = QtGui.QLabel(self.tab_7)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self._7.addWidget(self.label_29)
        self.lowResSmthKern_SB = QtGui.QSpinBox(self.tab_7)
        self.lowResSmthKern_SB.setProperty("value", QtCore.QVariant(15))
        self.lowResSmthKern_SB.setObjectName("lowResSmthKern_SB")
        self._7.addWidget(self.lowResSmthKern_SB)
        self.verticalLayout_3.addLayout(self._7)
        self._8 = QtGui.QHBoxLayout()
        self._8.setObjectName("_8")
        self.label_30 = QtGui.QLabel(self.tab_7)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self._8.addWidget(self.label_30)
        self.lowResPeakWidth_SB = QtGui.QSpinBox(self.tab_7)
        self.lowResPeakWidth_SB.setMinimum(3)
        self.lowResPeakWidth_SB.setMaximum(200000)
        self.lowResPeakWidth_SB.setProperty("value", QtCore.QVariant(100))
        self.lowResPeakWidth_SB.setObjectName("lowResPeakWidth_SB")
        self._8.addWidget(self.lowResPeakWidth_SB)
        self.verticalLayout_3.addLayout(self._8)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget_PP.addTab(self.tab_7, "")
        self.verticalLayout_6.addWidget(self.tabWidget_PP)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.useDefaultScale_CB = QtGui.QCheckBox(self.frame)
        self.useDefaultScale_CB.setChecked(False)
        self.useDefaultScale_CB.setObjectName("useDefaultScale_CB")
        self.vboxlayout2.addWidget(self.useDefaultScale_CB)
        self.hboxlayout15 = QtGui.QHBoxLayout()
        self.hboxlayout15.setObjectName("hboxlayout15")
        self.scaleStartLbl = QtGui.QLabel(self.frame)
        self.scaleStartLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scaleStartLbl.setObjectName("scaleStartLbl")
        self.hboxlayout15.addWidget(self.scaleStartLbl)
        self.scaleStart_SB = QtGui.QSpinBox(self.frame)
        self.scaleStart_SB.setMinimum(1)
        self.scaleStart_SB.setMaximum(10000)
        self.scaleStart_SB.setProperty("value", QtCore.QVariant(2))
        self.scaleStart_SB.setObjectName("scaleStart_SB")
        self.hboxlayout15.addWidget(self.scaleStart_SB)
        self.vboxlayout2.addLayout(self.hboxlayout15)
        self.hboxlayout16 = QtGui.QHBoxLayout()
        self.hboxlayout16.setObjectName("hboxlayout16")
        self.scaleEndLbl = QtGui.QLabel(self.frame)
        self.scaleEndLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scaleEndLbl.setObjectName("scaleEndLbl")
        self.hboxlayout16.addWidget(self.scaleEndLbl)
        self.scaleStop_SB = QtGui.QSpinBox(self.frame)
        self.scaleStop_SB.setMinimum(1)
        self.scaleStop_SB.setMaximum(10000)
        self.scaleStop_SB.setProperty("value", QtCore.QVariant(64))
        self.scaleStop_SB.setObjectName("scaleStop_SB")
        self.hboxlayout16.addWidget(self.scaleStop_SB)
        self.vboxlayout2.addLayout(self.hboxlayout16)
        self.hboxlayout17 = QtGui.QHBoxLayout()
        self.hboxlayout17.setObjectName("hboxlayout17")
        self.scaleFactorLbl = QtGui.QLabel(self.frame)
        self.scaleFactorLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scaleFactorLbl.setObjectName("scaleFactorLbl")
        self.hboxlayout17.addWidget(self.scaleFactorLbl)
        self.scaleFactor_SB = QtGui.QSpinBox(self.frame)
        self.scaleFactor_SB.setMinimum(1)
        self.scaleFactor_SB.setMaximum(100)
        self.scaleFactor_SB.setProperty("value", QtCore.QVariant(4))
        self.scaleFactor_SB.setObjectName("scaleFactor_SB")
        self.hboxlayout17.addWidget(self.scaleFactor_SB)
        self.vboxlayout2.addLayout(self.hboxlayout17)
        self.hboxlayout18 = QtGui.QHBoxLayout()
        self.hboxlayout18.setObjectName("hboxlayout18")
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.makeScales_Btn = QtGui.QPushButton(self.frame)
        self.makeScales_Btn.setObjectName("makeScales_Btn")
        self.vboxlayout3.addWidget(self.makeScales_Btn)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem5)
        self.hboxlayout18.addLayout(self.vboxlayout3)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout18.addItem(spacerItem6)
        self.vboxlayout2.addLayout(self.hboxlayout18)
        self.horizontalLayout.addLayout(self.vboxlayout2)
        self.hboxlayout19 = QtGui.QHBoxLayout()
        self.hboxlayout19.setObjectName("hboxlayout19")
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.scalesTable = QtGui.QTableWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scalesTable.sizePolicy().hasHeightForWidth())
        self.scalesTable.setSizePolicy(sizePolicy)
        self.scalesTable.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scalesTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scalesTable.setRowCount(8)
        self.scalesTable.setColumnCount(1)
        self.scalesTable.setObjectName("scalesTable")
        self.scalesTable.setColumnCount(1)
        self.scalesTable.setRowCount(8)
        self.vboxlayout4.addWidget(self.scalesTable)
        self.hboxlayout19.addLayout(self.vboxlayout4)
        spacerItem7 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout19.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.hboxlayout19)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.frame)
        self.tabWidget.addTab(self.optionsTab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout4 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout4.setObjectName("gridlayout4")
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vboxlayout5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setObjectName("vboxlayout6")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.vboxlayout6.addWidget(self.label)
        self.fpListWidget = QtGui.QListWidget(self.layoutWidget)
        self.fpListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fpListWidget.setObjectName("fpListWidget")
        self.vboxlayout6.addWidget(self.fpListWidget)
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setObjectName("gridlayout5")
        self.hboxlayout20 = QtGui.QHBoxLayout()
        self.hboxlayout20.setObjectName("hboxlayout20")
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.hboxlayout20.addWidget(self.label_42)
        self.freqCutoff_SB = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.freqCutoff_SB.setDecimals(2)
        self.freqCutoff_SB.setMinimum(0.01)
        self.freqCutoff_SB.setMaximum(1.0)
        self.freqCutoff_SB.setSingleStep(0.05)
        self.freqCutoff_SB.setProperty("value", QtCore.QVariant(0.5))
        self.freqCutoff_SB.setObjectName("freqCutoff_SB")
        self.hboxlayout20.addWidget(self.freqCutoff_SB)
        self.gridlayout5.addLayout(self.hboxlayout20, 0, 0, 1, 1)
        self.hboxlayout21 = QtGui.QHBoxLayout()
        self.hboxlayout21.setObjectName("hboxlayout21")
        self.label_43 = QtGui.QLabel(self.layoutWidget)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.hboxlayout21.addWidget(self.label_43)
        self.minSpectra_SB_6 = QtGui.QSpinBox(self.layoutWidget)
        self.minSpectra_SB_6.setEnabled(False)
        self.minSpectra_SB_6.setMinimum(1)
        self.minSpectra_SB_6.setProperty("value", QtCore.QVariant(3))
        self.minSpectra_SB_6.setObjectName("minSpectra_SB_6")
        self.hboxlayout21.addWidget(self.minSpectra_SB_6)
        self.gridlayout5.addLayout(self.hboxlayout21, 0, 2, 1, 1)
        self.hboxlayout22 = QtGui.QHBoxLayout()
        self.hboxlayout22.setObjectName("hboxlayout22")
        self.label_41 = QtGui.QLabel(self.layoutWidget)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.hboxlayout22.addWidget(self.label_41)
        self.alphaLvl_SB = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.alphaLvl_SB.setDecimals(2)
        self.alphaLvl_SB.setMinimum(0.01)
        self.alphaLvl_SB.setMaximum(1.0)
        self.alphaLvl_SB.setSingleStep(0.05)
        self.alphaLvl_SB.setProperty("value", QtCore.QVariant(0.05))
        self.alphaLvl_SB.setObjectName("alphaLvl_SB")
        self.hboxlayout22.addWidget(self.alphaLvl_SB)
        self.gridlayout5.addLayout(self.hboxlayout22, 0, 1, 1, 1)
        self.vboxlayout6.addLayout(self.gridlayout5)
        self.hboxlayout23 = QtGui.QHBoxLayout()
        self.hboxlayout23.setObjectName("hboxlayout23")
        self.loadFP_Btn = QtGui.QPushButton(self.layoutWidget)
        self.loadFP_Btn.setObjectName("loadFP_Btn")
        self.hboxlayout23.addWidget(self.loadFP_Btn)
        self.loadRawFPData_CB = QtGui.QCheckBox(self.layoutWidget)
        self.loadRawFPData_CB.setObjectName("loadRawFPData_CB")
        self.hboxlayout23.addWidget(self.loadRawFPData_CB)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout23.addItem(spacerItem8)
        self.vboxlayout6.addLayout(self.hboxlayout23)
        self.vboxlayout5.addLayout(self.vboxlayout6)
        self.hboxlayout24 = QtGui.QHBoxLayout()
        self.hboxlayout24.setObjectName("hboxlayout24")
        self.autoLoadFP_CB = QtGui.QCheckBox(self.layoutWidget)
        self.autoLoadFP_CB.setObjectName("autoLoadFP_CB")
        self.hboxlayout24.addWidget(self.autoLoadFP_CB)
        self.curFPName_LE = QtGui.QLineEdit(self.layoutWidget)
        self.curFPName_LE.setReadOnly(True)
        self.curFPName_LE.setObjectName("curFPName_LE")
        self.hboxlayout24.addWidget(self.curFPName_LE)
        self.vboxlayout5.addLayout(self.hboxlayout24)
        self.fingerPTable = CustomTable(self.layoutWidget)
        self.fingerPTable.setObjectName("fingerPTable")
        self.fingerPTable.setColumnCount(0)
        self.fingerPTable.setRowCount(0)
        self.vboxlayout5.addWidget(self.fingerPTable)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hboxlayout25 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.hboxlayout25.setObjectName("hboxlayout25")
        self.vboxlayout7 = QtGui.QVBoxLayout()
        self.vboxlayout7.setObjectName("vboxlayout7")
        self.doPCA_Btn = QtGui.QToolButton(self.layoutWidget1)
        self.doPCA_Btn.setMinimumSize(QtCore.QSize(30, 30))
        self.doPCA_Btn.setObjectName("doPCA_Btn")
        self.vboxlayout7.addWidget(self.doPCA_Btn)
        self.doFP_Btn = QtGui.QToolButton(self.layoutWidget1)
        self.doFP_Btn.setMinimumSize(QtCore.QSize(30, 30))
        self.doFP_Btn.setObjectName("doFP_Btn")
        self.vboxlayout7.addWidget(self.doFP_Btn)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout7.addItem(spacerItem9)
        self.hboxlayout25.addLayout(self.vboxlayout7)
        self.vboxlayout8 = QtGui.QVBoxLayout()
        self.vboxlayout8.setObjectName("vboxlayout8")
        self.hboxlayout26 = QtGui.QHBoxLayout()
        self.hboxlayout26.setObjectName("hboxlayout26")
        self.expand_Btn = QtGui.QPushButton(self.layoutWidget1)
        self.expand_Btn.setObjectName("expand_Btn")
        self.hboxlayout26.addWidget(self.expand_Btn)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout26.addItem(spacerItem10)
        self.vboxlayout8.addLayout(self.hboxlayout26)
        self.fpSpecTreeWidget = QtGui.QTreeWidget(self.layoutWidget1)
        self.fpSpecTreeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fpSpecTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fpSpecTreeWidget.setHeaderHidden(False)
        self.fpSpecTreeWidget.setColumnCount(1)
        self.fpSpecTreeWidget.setObjectName("fpSpecTreeWidget")
        self.vboxlayout8.addWidget(self.fpSpecTreeWidget)
        self.hboxlayout25.addLayout(self.vboxlayout8)
        self.gridlayout4.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.vboxlayout9 = QtGui.QVBoxLayout(self.tab_3)
        self.vboxlayout9.setObjectName("vboxlayout9")
        self.gridlayout6 = QtGui.QGridLayout()
        self.gridlayout6.setObjectName("gridlayout6")
        self.vboxlayout10 = QtGui.QVBoxLayout()
        self.vboxlayout10.setObjectName("vboxlayout10")
        self.hboxlayout27 = QtGui.QHBoxLayout()
        self.hboxlayout27.setObjectName("hboxlayout27")
        self.fpFolder_Btn = QtGui.QPushButton(self.tab_3)
        self.fpFolder_Btn.setEnabled(True)
        self.fpFolder_Btn.setObjectName("fpFolder_Btn")
        self.hboxlayout27.addWidget(self.fpFolder_Btn)
        self.fpFolder_LE = QtGui.QLineEdit(self.tab_3)
        self.fpFolder_LE.setReadOnly(True)
        self.fpFolder_LE.setObjectName("fpFolder_LE")
        self.hboxlayout27.addWidget(self.fpFolder_LE)
        self.vboxlayout10.addLayout(self.hboxlayout27)
        self.hboxlayout28 = QtGui.QHBoxLayout()
        self.hboxlayout28.setObjectName("hboxlayout28")
        self.savePref_Btn = QtGui.QPushButton(self.tab_3)
        self.savePref_Btn.setObjectName("savePref_Btn")
        self.hboxlayout28.addWidget(self.savePref_Btn)
        self.revert_Btn = QtGui.QPushButton(self.tab_3)
        self.revert_Btn.setObjectName("revert_Btn")
        self.hboxlayout28.addWidget(self.revert_Btn)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout28.addItem(spacerItem11)
        self.vboxlayout10.addLayout(self.hboxlayout28)
        self.gridlayout6.addLayout(self.vboxlayout10, 0, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout6.addItem(spacerItem13, 1, 0, 1, 1)
        self.vboxlayout9.addLayout(self.gridlayout6)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridlayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionCursor_A = QtGui.QAction(MainWindow)
        self.actionCursor_A.setObjectName("actionCursor_A")
        self.actionCursor_B = QtGui.QAction(MainWindow)
        self.actionCursor_B.setObjectName("actionCursor_B")
        self.actionLabel_Peak = QtGui.QAction(MainWindow)
        self.actionLabel_Peak.setObjectName("actionLabel_Peak")
        self.actionCopy_to_Clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_to_Clipboard.setObjectName("actionCopy_to_Clipboard")
        self.actionClear_Cursors = QtGui.QAction(MainWindow)
        self.actionClear_Cursors.setObjectName("actionClear_Cursors")
        self.actionRead_Me = QtGui.QAction(MainWindow)
        self.actionRead_Me.setObjectName("actionRead_Me")
        self.actionPeak_Picking = QtGui.QAction(MainWindow)
        self.actionPeak_Picking.setObjectName("actionPeak_Picking")
        self.actionFind_Peaks = QtGui.QAction(MainWindow)
        self.actionFind_Peaks.setObjectName("actionFind_Peaks")
        self.actionExit_Program = QtGui.QAction(MainWindow)
        self.actionExit_Program.setObjectName("actionExit_Program")
        self.actionHelpFingerPrint = QtGui.QAction(MainWindow)
        self.actionHelpFingerPrint.setObjectName("actionHelpFingerPrint")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit_Program)
        self.menuTools.addAction(self.actionCursor_A)
        self.menuTools.addAction(self.actionCursor_B)
        self.menuTools.addAction(self.actionClear_Cursors)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionLabel_Peak)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionFind_Peaks)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCopy_to_Clipboard)
        self.menu_Help.addAction(self.actionRead_Me)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_PP.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SpectrumViewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Spectrum Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTreeWidget.setSortingEnabled(True)
        self.groupTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.multiPlot_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enable if multiple spectral overlays are desired.  Keep in mind the memory requirments.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.multiPlot_CB.setText(QtGui.QApplication.translate("MainWindow", "Enable Multiplot?", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Zoom Window (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomPercent_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomPercent_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomPercent_CB.setItemText(2, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomPercent_CB.setItemText(3, QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomPercent_CB.setItemText(4, QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Peak Table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Index:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Index:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "dx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "dy:", None, QtGui.QApplication.UnicodeUTF8))
        self.cursACB.setText(QtGui.QApplication.translate("MainWindow", "Cursor A", None, QtGui.QApplication.UnicodeUTF8))
        self.cursBCB.setText(QtGui.QApplication.translate("MainWindow", "Cursor B", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.loadmzXMLCB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uncheck to load Bruker fid files.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Keep in mind that only LIFT files</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">that have been converted to mzXML</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">can be loaded.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadmzXMLCB.setText(QtGui.QApplication.translate("MainWindow", "Load mzXML", None, QtGui.QApplication.UnicodeUTF8))
        self.plotLegendCB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Include plot legend by default?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.plotLegendCB.setText(QtGui.QApplication.translate("MainWindow", "Plot Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.plotPkListCB.setText(QtGui.QApplication.translate("MainWindow", "Plot Peak List", None, QtGui.QApplication.UnicodeUTF8))
        self.autoSavePkList_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.autoSavePkList_CB.setText(QtGui.QApplication.translate("MainWindow", "Auto-save Found Peaks?", None, QtGui.QApplication.UnicodeUTF8))
        self.excludeLIFTCB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ignore LIFT files when loading data?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.excludeLIFTCB.setText(QtGui.QApplication.translate("MainWindow", "Exclude LIFT MS/MS Files", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPeak_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Label picked peaks when plotting?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPeak_CB.setText(QtGui.QApplication.translate("MainWindow", "Label Peaks?", None, QtGui.QApplication.UnicodeUTF8))
        self.plotNoiseEst_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Include noise estimate when plotting?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.plotNoiseEst_CB.setText(QtGui.QApplication.translate("MainWindow", "Show Noise Estimate", None, QtGui.QApplication.UnicodeUTF8))
        self.invertCompCB.setText(QtGui.QApplication.translate("MainWindow", "Invert Single Comparison", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Global ppm Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "m/z Lo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "m/z Hi:", None, QtGui.QApplication.UnicodeUTF8))
        self.mzHi_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "If this value is set to -1 then a TIC starting from m/z Lo will be returned", None, QtGui.QApplication.UnicodeUTF8))
        self.getEIC_Btn.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Create an EIC for all members within a selected group.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.getEIC_Btn.setText(QtGui.QApplication.translate("MainWindow", "Fetch EIC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Peak Picking Algorithm:", None, QtGui.QApplication.UnicodeUTF8))
        self.peakPick_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "High Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.peakPick_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "Standard Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.peakPick_CB.setItemText(2, QtGui.QApplication.translate("MainWindow", "Low Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("MainWindow", "SNR value used for noise estimate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "SNR Noise Estimation:", None, QtGui.QApplication.UnicodeUTF8))
        self.snrNoiseEst_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">SNR value used for noise estimate</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Wavelet Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">DOG -- Derivative of Gaussian</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Mexican Hat</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">More later...</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "DOG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mexican Hat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Estimate Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Correlation Cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Isotope fits below this value will be excluded from the peak list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_PP.setTabText(self.tabWidget_PP.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "High Res.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Auto Peak Setting:", None, QtGui.QApplication.UnicodeUTF8))
        self.peakSetting_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Peak Picking Presets</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "End of Wavelet Noise Rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.minRow_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Last row of the wavelet to be considered noise.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Must be less than the number of scales.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">A smaller number means more peaks,</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">but not necessarily better results.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Minimum Wavelet Cluster Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.minClust_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "Minimum number of peaks to be found during the wavelet transform for each MS peak.\n"
"Must be less than the number of scales.\n"
"Half the number of scales appears to be a good approximation.\n"
"Higher numbers mean fewer peaks.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Wavelet Row Tolerance:", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletRowTol_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Allowed tolerance for each peak found in each subsequent row of the wavelet transform.  A smaller number requires tighter grouping of peaks for each scale of the CWT in order for a peak to be located.  Too large a number creates more peaks, but at a cost.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Clustering Distance Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.dbscanEPS_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Distance to be used for a clustering cutoff.  Set to -1 for auto-calculation.  A smaller number means fewer peaks while a larger number includes more surrounding neighbors.  Be careful...</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Noise Split Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.noiseFactor_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Factor by which the spectrum will be split in order to estimate local noise.  More is better but slower. For example:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">if the length of a MS spectrum = 10000</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">and Noise Split Factor = 10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">the number of segments used = 1000</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Static Cutoff:", None, QtGui.QApplication.UnicodeUTF8))
        self.staticCutoff_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">This is the minimum value in absolute counts (i.e. not normalized) to be considered for peak picking.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.showCWT_CB.setText(QtGui.QApplication.translate("MainWindow", "Show CWT with Peak Picking?", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_PP.setTabText(self.tabWidget_PP.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Standard Res.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Minimum Signal-to-Noise:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Slope Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Smoothing Kernel Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Approximate Peak Width (in points):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_PP.setTabText(self.tabWidget_PP.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Low Res.", None, QtGui.QApplication.UnicodeUTF8))
        self.useDefaultScale_CB.setText(QtGui.QApplication.translate("MainWindow", "Use Default Scales for CWT", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleStartLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Factor by which the spectrum will be split in order to estimate local noise", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleStartLbl.setText(QtGui.QApplication.translate("MainWindow", "Scale Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleStart_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Starting point for scales</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleEndLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Factor by which the spectrum will be split in order to estimate local noise", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleEndLbl.setText(QtGui.QApplication.translate("MainWindow", "Scale End:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleStop_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">End point for scales.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleFactorLbl.setToolTip(QtGui.QApplication.translate("MainWindow", "Factor by which the spectrum will be split in order to estimate local noise", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleFactorLbl.setText(QtGui.QApplication.translate("MainWindow", "Scale Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleFactor_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Don\'t Mess with this unless you know what you\'re doing!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Making too many scales will slow things WAAAY down!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.makeScales_Btn.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Try to keep the total number of scales below 10,</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">otherwise peak picking could take a while.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Example of use:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Scale Start: 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Scale End: 32</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Scale Factor: 4</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Output Scales:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">[ 2,  6, 10, 14, 18, 22, 26, 30]</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.makeScales_Btn.setText(QtGui.QApplication.translate("MainWindow", "Create Scales", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionsTab), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Available Fingerprints:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Freq Cutoff:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Min # of Spectra:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Significance Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFP_Btn.setText(QtGui.QApplication.translate("MainWindow", "Load Fingerprint", None, QtGui.QApplication.UnicodeUTF8))
        self.loadRawFPData_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">By checking this box, if you open a saved FP, all of the raw data will also be loaded.  This can be useful if a new FP is needed.  Be aware that for large FP this could significantly slow your machine...</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadRawFPData_CB.setText(QtGui.QApplication.translate("MainWindow", "Load Raw Data From FP?", None, QtGui.QApplication.UnicodeUTF8))
        self.autoLoadFP_CB.setText(QtGui.QApplication.translate("MainWindow", "Auto Load Fingerprints", None, QtGui.QApplication.UnicodeUTF8))
        self.doPCA_Btn.setText(QtGui.QApplication.translate("MainWindow", "PCA", None, QtGui.QApplication.UnicodeUTF8))
        self.doFP_Btn.setText(QtGui.QApplication.translate("MainWindow", "FP", None, QtGui.QApplication.UnicodeUTF8))
        self.expand_Btn.setText(QtGui.QApplication.translate("MainWindow", "Expand or Collapse All", None, QtGui.QApplication.UnicodeUTF8))
        self.fpSpecTreeWidget.setSortingEnabled(True)
        self.fpSpecTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Fingerprint", None, QtGui.QApplication.UnicodeUTF8))
        self.fpFolder_Btn.setText(QtGui.QApplication.translate("MainWindow", "Default Fingerprint Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.savePref_Btn.setText(QtGui.QApplication.translate("MainWindow", "Save Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.revert_Btn.setText(QtGui.QApplication.translate("MainWindow", "Revert to Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCursor_A.setText(QtGui.QApplication.translate("MainWindow", "Cursor A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCursor_B.setText(QtGui.QApplication.translate("MainWindow", "Cursor B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLabel_Peak.setText(QtGui.QApplication.translate("MainWindow", "Label Peak", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLabel_Peak.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_to_Clipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy Plot to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cursors.setText(QtGui.QApplication.translate("MainWindow", "Clear Cursors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cursors.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRead_Me.setText(QtGui.QApplication.translate("MainWindow", "Read Me", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPeak_Picking.setText(QtGui.QApplication.translate("MainWindow", "About Peak Picking", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Peaks.setText(QtGui.QApplication.translate("MainWindow", "Find Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_Program.setText(QtGui.QApplication.translate("MainWindow", "Exit Program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpFingerPrint.setText(QtGui.QApplication.translate("MainWindow", "Finger Printing", None, QtGui.QApplication.UnicodeUTF8))

from customTable import CustomTable
from mpl_pyqt4_widget import MPL_Widget
import icons_rc
