# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\d3p483\workspace\NoiseProject\main.ui'
#
# Created: Tue Jun 02 11:13:31 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 687)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Retro Mario World_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridlayout = QtGui.QGridLayout(self.centralwidget)
        self.gridlayout.setObjectName("gridlayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.gridLayout = QtGui.QGridLayout(self.plotTab)
        self.gridLayout.setObjectName("gridLayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_2 = QtGui.QLabel(self.plotTab)
        self.label_2.setObjectName("label_2")
        self.hboxlayout.addWidget(self.label_2)
        self.specNameEdit = QtGui.QLineEdit(self.plotTab)
        self.specNameEdit.setReadOnly(True)
        self.specNameEdit.setObjectName("specNameEdit")
        self.hboxlayout.addWidget(self.specNameEdit)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_13 = QtGui.QLabel(self.plotTab)
        self.label_13.setObjectName("label_13")
        self.hboxlayout1.addWidget(self.label_13)
        self.hSlider_Freq = QtGui.QSlider(self.plotTab)
        self.hSlider_Freq.setEnabled(False)
        self.hSlider_Freq.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_Freq.setObjectName("hSlider_Freq")
        self.hboxlayout1.addWidget(self.hSlider_Freq)
        self.freqCutoff_SB = QtGui.QDoubleSpinBox(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqCutoff_SB.sizePolicy().hasHeightForWidth())
        self.freqCutoff_SB.setSizePolicy(sizePolicy)
        self.freqCutoff_SB.setMinimum(0.05)
        self.freqCutoff_SB.setMaximum(1000000.0)
        self.freqCutoff_SB.setProperty("value", QtCore.QVariant(85.0))
        self.freqCutoff_SB.setObjectName("freqCutoff_SB")
        self.hboxlayout1.addWidget(self.freqCutoff_SB)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.plotWidget = MPL_Widget(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.vboxlayout.addWidget(self.plotWidget)
        self.gridLayout.addLayout(self.vboxlayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtGui.QTabWidget(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridlayout1 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout1.setObjectName("gridlayout1")
        self.groupTreeWidget = QtGui.QTreeWidget(self.tab_3)
        self.groupTreeWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.groupTreeWidget.setHeaderHidden(False)
        self.groupTreeWidget.setColumnCount(1)
        self.groupTreeWidget.setObjectName("groupTreeWidget")
        self.gridlayout1.addWidget(self.groupTreeWidget, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridlayout2 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout2.setObjectName("gridlayout2")
        self.fileInfo_TE = QtGui.QTextEdit(self.tab_4)
        self.fileInfo_TE.setObjectName("fileInfo_TE")
        self.gridlayout2.addWidget(self.fileInfo_TE, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadWSU_CB = QtGui.QCheckBox(self.plotTab)
        self.loadWSU_CB.setChecked(True)
        self.loadWSU_CB.setObjectName("loadWSU_CB")
        self.horizontalLayout_3.addWidget(self.loadWSU_CB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_15 = QtGui.QLabel(self.plotTab)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.hboxlayout2.addWidget(self.label_15)
        self.filterInfo_LE = QtGui.QLineEdit(self.plotTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterInfo_LE.sizePolicy().hasHeightForWidth())
        self.filterInfo_LE.setSizePolicy(sizePolicy)
        self.filterInfo_LE.setReadOnly(True)
        self.filterInfo_LE.setObjectName("filterInfo_LE")
        self.hboxlayout2.addWidget(self.filterInfo_LE)
        self.verticalLayout_2.addLayout(self.hboxlayout2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setHorizontalSpacing(3)
        self.gridlayout3.setVerticalSpacing(2)
        self.gridlayout3.setObjectName("gridlayout3")
        self.cALabelLE = QtGui.QLineEdit(self.plotTab)
        self.cALabelLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cALabelLE.setFont(font)
        self.cALabelLE.setReadOnly(True)
        self.cALabelLE.setObjectName("cALabelLE")
        self.gridlayout3.addWidget(self.cALabelLE, 0, 3, 1, 1)
        self.cAIndexLE = QtGui.QLineEdit(self.plotTab)
        self.cAIndexLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cAIndexLE.setFont(font)
        self.cAIndexLE.setReadOnly(True)
        self.cAIndexLE.setObjectName("cAIndexLE")
        self.gridlayout3.addWidget(self.cAIndexLE, 0, 5, 1, 1)
        self.cA_XLE = QtGui.QLineEdit(self.plotTab)
        self.cA_XLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cA_XLE.setFont(font)
        self.cA_XLE.setReadOnly(True)
        self.cA_XLE.setObjectName("cA_XLE")
        self.gridlayout3.addWidget(self.cA_XLE, 0, 7, 1, 1)
        self.cA_YLE = QtGui.QLineEdit(self.plotTab)
        self.cA_YLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cA_YLE.setFont(font)
        self.cA_YLE.setReadOnly(True)
        self.cA_YLE.setObjectName("cA_YLE")
        self.gridlayout3.addWidget(self.cA_YLE, 0, 9, 1, 1)
        self.cBLabelLE = QtGui.QLineEdit(self.plotTab)
        self.cBLabelLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cBLabelLE.setFont(font)
        self.cBLabelLE.setReadOnly(True)
        self.cBLabelLE.setObjectName("cBLabelLE")
        self.gridlayout3.addWidget(self.cBLabelLE, 1, 3, 1, 1)
        self.cBIndexLE = QtGui.QLineEdit(self.plotTab)
        self.cBIndexLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cBIndexLE.setFont(font)
        self.cBIndexLE.setReadOnly(True)
        self.cBIndexLE.setObjectName("cBIndexLE")
        self.gridlayout3.addWidget(self.cBIndexLE, 1, 5, 1, 1)
        self.cB_XLE = QtGui.QLineEdit(self.plotTab)
        self.cB_XLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cB_XLE.setFont(font)
        self.cB_XLE.setReadOnly(True)
        self.cB_XLE.setObjectName("cB_XLE")
        self.gridlayout3.addWidget(self.cB_XLE, 1, 7, 1, 1)
        self.cB_YLE = QtGui.QLineEdit(self.plotTab)
        self.cB_YLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cB_YLE.setFont(font)
        self.cB_YLE.setReadOnly(True)
        self.cB_YLE.setObjectName("cB_YLE")
        self.gridlayout3.addWidget(self.cB_YLE, 1, 9, 1, 1)
        self.label_3 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridlayout3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridlayout3.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridlayout3.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridlayout3.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridlayout3.addWidget(self.label_7, 0, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridlayout3.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridlayout3.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_10 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridlayout3.addWidget(self.label_10, 1, 8, 1, 1)
        self.label_11 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridlayout3.addWidget(self.label_11, 0, 10, 1, 1)
        self.label_12 = QtGui.QLabel(self.plotTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridlayout3.addWidget(self.label_12, 1, 10, 1, 1)
        self.dxLE = QtGui.QLineEdit(self.plotTab)
        self.dxLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.dxLE.setFont(font)
        self.dxLE.setReadOnly(True)
        self.dxLE.setObjectName("dxLE")
        self.gridlayout3.addWidget(self.dxLE, 0, 11, 1, 1)
        self.dyLE = QtGui.QLineEdit(self.plotTab)
        self.dyLE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.dyLE.setFont(font)
        self.dyLE.setReadOnly(True)
        self.dyLE.setObjectName("dyLE")
        self.gridlayout3.addWidget(self.dyLE, 1, 11, 1, 1)
        self.cursACB = QtGui.QCheckBox(self.plotTab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.cursACB.setFont(font)
        self.cursACB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cursACB.setObjectName("cursACB")
        self.gridlayout3.addWidget(self.cursACB, 0, 0, 1, 1)
        self.cursBCB = QtGui.QCheckBox(self.plotTab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.cursBCB.setFont(font)
        self.cursBCB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cursBCB.setObjectName("cursBCB")
        self.gridlayout3.addWidget(self.cursBCB, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.plotTab)
        self.label_21.setTextFormat(QtCore.Qt.RichText)
        self.label_21.setObjectName("label_21")
        self.gridlayout3.addWidget(self.label_21, 0, 12, 1, 1)
        self.label_22 = QtGui.QLabel(self.plotTab)
        self.label_22.setTextFormat(QtCore.Qt.RichText)
        self.label_22.setObjectName("label_22")
        self.gridlayout3.addWidget(self.label_22, 1, 12, 1, 1)
        self.curAMob_LE = QtGui.QLineEdit(self.plotTab)
        self.curAMob_LE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.curAMob_LE.setFont(font)
        self.curAMob_LE.setObjectName("curAMob_LE")
        self.gridlayout3.addWidget(self.curAMob_LE, 0, 13, 1, 1)
        self.curBMob_LE = QtGui.QLineEdit(self.plotTab)
        self.curBMob_LE.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.curBMob_LE.setFont(font)
        self.curBMob_LE.setObjectName("curBMob_LE")
        self.gridlayout3.addWidget(self.curBMob_LE, 1, 13, 1, 1)
        self.gridLayout.addLayout(self.gridlayout3, 1, 0, 1, 2)
        self.tabWidget.addTab(self.plotTab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridlayout4 = QtGui.QGridLayout(self.tab)
        self.gridlayout4.setObjectName("gridlayout4")
        self.rawDataTable = CustomTable(self.tab)
        self.rawDataTable.setObjectName("rawDataTable")
        self.rawDataTable.setColumnCount(0)
        self.rawDataTable.setRowCount(0)
        self.gridlayout4.addWidget(self.rawDataTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridlayout5 = QtGui.QGridLayout()
        self.gridlayout5.setObjectName("gridlayout5")
        self.plotLegendCB = QtGui.QCheckBox(self.tab_2)
        self.plotLegendCB.setChecked(True)
        self.plotLegendCB.setObjectName("plotLegendCB")
        self.gridlayout5.addWidget(self.plotLegendCB, 0, 0, 1, 1)
        self.invertCompCB = QtGui.QCheckBox(self.tab_2)
        self.invertCompCB.setChecked(True)
        self.invertCompCB.setObjectName("invertCompCB")
        self.gridlayout5.addWidget(self.invertCompCB, 1, 0, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.lowPassOn_CB = QtGui.QCheckBox(self.tab_2)
        self.lowPassOn_CB.setChecked(True)
        self.lowPassOn_CB.setObjectName("lowPassOn_CB")
        self.hboxlayout3.addWidget(self.lowPassOn_CB)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.vboxlayout1.addWidget(self.label)
        self.sgKernel_SB = QtGui.QSpinBox(self.tab_2)
        self.sgKernel_SB.setMinimum(1)
        self.sgKernel_SB.setSingleStep(1)
        self.sgKernel_SB.setProperty("value", QtCore.QVariant(17))
        self.sgKernel_SB.setObjectName("sgKernel_SB")
        self.vboxlayout1.addWidget(self.sgKernel_SB)
        self.hboxlayout4.addLayout(self.vboxlayout1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.vboxlayout2.addWidget(self.label_14)
        self.sgOrder_SB = QtGui.QSpinBox(self.tab_2)
        self.sgOrder_SB.setMinimum(1)
        self.sgOrder_SB.setProperty("value", QtCore.QVariant(3))
        self.sgOrder_SB.setObjectName("sgOrder_SB")
        self.vboxlayout2.addWidget(self.sgOrder_SB)
        self.hboxlayout4.addLayout(self.vboxlayout2)
        self.hboxlayout3.addLayout(self.hboxlayout4)
        self.gridlayout5.addLayout(self.hboxlayout3, 1, 1, 2, 1)
        self.ignoreRaw_CB = QtGui.QCheckBox(self.tab_2)
        self.ignoreRaw_CB.setObjectName("ignoreRaw_CB")
        self.gridlayout5.addWidget(self.ignoreRaw_CB, 2, 0, 1, 1)
        self.normRaw_CB = QtGui.QCheckBox(self.tab_2)
        self.normRaw_CB.setChecked(True)
        self.normRaw_CB.setObjectName("normRaw_CB")
        self.gridlayout5.addWidget(self.normRaw_CB, 3, 0, 1, 1)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.hboxlayout5.addWidget(self.label_20)
        self.driftLength_SB = QtGui.QDoubleSpinBox(self.tab_2)
        self.driftLength_SB.setMinimum(0.01)
        self.driftLength_SB.setMaximum(1000.0)
        self.driftLength_SB.setProperty("value", QtCore.QVariant(15.0))
        self.driftLength_SB.setObjectName("driftLength_SB")
        self.hboxlayout5.addWidget(self.driftLength_SB)
        self.gridlayout5.addLayout(self.hboxlayout5, 4, 0, 1, 1)
        self._3 = QtGui.QHBoxLayout()
        self._3.setObjectName("_3")
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self._3.addWidget(self.label_24)
        self.pressure_SB = QtGui.QDoubleSpinBox(self.tab_2)
        self.pressure_SB.setMinimum(0.01)
        self.pressure_SB.setMaximum(1000.0)
        self.pressure_SB.setProperty("value", QtCore.QVariant(700.0))
        self.pressure_SB.setObjectName("pressure_SB")
        self._3.addWidget(self.pressure_SB)
        self.gridlayout5.addLayout(self._3, 5, 0, 1, 1)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName("_2")
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self._2.addWidget(self.label_23)
        self.voltage_SB = QtGui.QDoubleSpinBox(self.tab_2)
        self.voltage_SB.setMinimum(0.01)
        self.voltage_SB.setMaximum(100000.0)
        self.voltage_SB.setSingleStep(25.0)
        self.voltage_SB.setProperty("value", QtCore.QVariant(7500.0))
        self.voltage_SB.setObjectName("voltage_SB")
        self._2.addWidget(self.voltage_SB)
        self.gridlayout5.addLayout(self._2, 4, 1, 1, 1)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName("_4")
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self._4.addWidget(self.label_25)
        self.temp_SB = QtGui.QDoubleSpinBox(self.tab_2)
        self.temp_SB.setMinimum(0.01)
        self.temp_SB.setMaximum(1000.0)
        self.temp_SB.setProperty("value", QtCore.QVariant(180.0))
        self.temp_SB.setObjectName("temp_SB")
        self._4.addWidget(self.temp_SB)
        self.gridlayout5.addLayout(self._4, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridlayout6 = QtGui.QGridLayout(self.tab_5)
        self.gridlayout6.setObjectName("gridlayout6")
        self.imRpWidget = MPL_Widget(self.tab_5)
        self.imRpWidget.setObjectName("imRpWidget")
        self.gridlayout6.addWidget(self.imRpWidget, 0, 0, 1, 1)
        self.gridlayout7 = QtGui.QGridLayout()
        self.gridlayout7.setObjectName("gridlayout7")
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setObjectName("label_16")
        self.hboxlayout6.addWidget(self.label_16)
        self.tempSlider = QtGui.QSlider(self.tab_5)
        self.tempSlider.setMinimum(1)
        self.tempSlider.setMaximum(500)
        self.tempSlider.setProperty("value", QtCore.QVariant(180))
        self.tempSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tempSlider.setObjectName("tempSlider")
        self.hboxlayout6.addWidget(self.tempSlider)
        self.sliderTemp_SB = QtGui.QDoubleSpinBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderTemp_SB.sizePolicy().hasHeightForWidth())
        self.sliderTemp_SB.setSizePolicy(sizePolicy)
        self.sliderTemp_SB.setMinimum(0.01)
        self.sliderTemp_SB.setMaximum(500.0)
        self.sliderTemp_SB.setProperty("value", QtCore.QVariant(180.0))
        self.sliderTemp_SB.setObjectName("sliderTemp_SB")
        self.hboxlayout6.addWidget(self.sliderTemp_SB)
        self.gridlayout7.addLayout(self.hboxlayout6, 0, 0, 1, 1)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label_17 = QtGui.QLabel(self.tab_5)
        self.label_17.setObjectName("label_17")
        self.hboxlayout7.addWidget(self.label_17)
        self.voltageSlider = QtGui.QSlider(self.tab_5)
        self.voltageSlider.setMinimum(1)
        self.voltageSlider.setMaximum(25000)
        self.voltageSlider.setProperty("value", QtCore.QVariant(8000))
        self.voltageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.voltageSlider.setObjectName("voltageSlider")
        self.hboxlayout7.addWidget(self.voltageSlider)
        self.sliderVoltage_SB = QtGui.QDoubleSpinBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderVoltage_SB.sizePolicy().hasHeightForWidth())
        self.sliderVoltage_SB.setSizePolicy(sizePolicy)
        self.sliderVoltage_SB.setMinimum(1.0)
        self.sliderVoltage_SB.setMaximum(25000.0)
        self.sliderVoltage_SB.setSingleStep(1.0)
        self.sliderVoltage_SB.setProperty("value", QtCore.QVariant(8000.0))
        self.sliderVoltage_SB.setObjectName("sliderVoltage_SB")
        self.hboxlayout7.addWidget(self.sliderVoltage_SB)
        self.gridlayout7.addLayout(self.hboxlayout7, 1, 0, 1, 1)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label_18 = QtGui.QLabel(self.tab_5)
        self.label_18.setObjectName("label_18")
        self.hboxlayout8.addWidget(self.label_18)
        self.gatePWSlider = QtGui.QSlider(self.tab_5)
        self.gatePWSlider.setMinimum(1)
        self.gatePWSlider.setMaximum(10000)
        self.gatePWSlider.setSingleStep(50)
        self.gatePWSlider.setProperty("value", QtCore.QVariant(200))
        self.gatePWSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gatePWSlider.setObjectName("gatePWSlider")
        self.hboxlayout8.addWidget(self.gatePWSlider)
        self.sliderGPW_SB = QtGui.QDoubleSpinBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderGPW_SB.sizePolicy().hasHeightForWidth())
        self.sliderGPW_SB.setSizePolicy(sizePolicy)
        self.sliderGPW_SB.setMinimum(0.01)
        self.sliderGPW_SB.setMaximum(10000.0)
        self.sliderGPW_SB.setSingleStep(50.0)
        self.sliderGPW_SB.setProperty("value", QtCore.QVariant(200.0))
        self.sliderGPW_SB.setObjectName("sliderGPW_SB")
        self.hboxlayout8.addWidget(self.sliderGPW_SB)
        self.gridlayout7.addLayout(self.hboxlayout8, 2, 0, 1, 1)
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setObjectName("label_19")
        self.hboxlayout9.addWidget(self.label_19)
        self.driftTimeSlider = QtGui.QSlider(self.tab_5)
        self.driftTimeSlider.setMinimum(1)
        self.driftTimeSlider.setMaximum(1000)
        self.driftTimeSlider.setProperty("value", QtCore.QVariant(25))
        self.driftTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.driftTimeSlider.setObjectName("driftTimeSlider")
        self.hboxlayout9.addWidget(self.driftTimeSlider)
        self.sliderDriftTime_SB = QtGui.QDoubleSpinBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderDriftTime_SB.sizePolicy().hasHeightForWidth())
        self.sliderDriftTime_SB.setSizePolicy(sizePolicy)
        self.sliderDriftTime_SB.setMinimum(0.01)
        self.sliderDriftTime_SB.setMaximum(1000.0)
        self.sliderDriftTime_SB.setSingleStep(1.0)
        self.sliderDriftTime_SB.setProperty("value", QtCore.QVariant(25.0))
        self.sliderDriftTime_SB.setObjectName("sliderDriftTime_SB")
        self.hboxlayout9.addWidget(self.sliderDriftTime_SB)
        self.gridlayout7.addLayout(self.hboxlayout9, 3, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridlayout7.addWidget(self.doubleSpinBox_5, 4, 0, 1, 1)
        self.gridlayout6.addLayout(self.gridlayout7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionCursor_A = QtGui.QAction(MainWindow)
        self.actionCursor_A.setObjectName("actionCursor_A")
        self.actionCursor_B = QtGui.QAction(MainWindow)
        self.actionCursor_B.setObjectName("actionCursor_B")
        self.actionLabel_Peak = QtGui.QAction(MainWindow)
        self.actionLabel_Peak.setObjectName("actionLabel_Peak")
        self.actionCopy_to_Clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_to_Clipboard.setObjectName("actionCopy_to_Clipboard")
        self.actionClear_Cursors = QtGui.QAction(MainWindow)
        self.actionClear_Cursors.setObjectName("actionClear_Cursors")
        self.actionRead_Me = QtGui.QAction(MainWindow)
        self.actionRead_Me.setObjectName("actionRead_Me")
        self.actionPeak_Picking = QtGui.QAction(MainWindow)
        self.actionPeak_Picking.setObjectName("actionPeak_Picking")
        self.actionFind_Peaks = QtGui.QAction(MainWindow)
        self.actionFind_Peaks.setObjectName("actionFind_Peaks")
        self.actionExit_Program = QtGui.QAction(MainWindow)
        self.actionExit_Program.setObjectName("actionExit_Program")
        self.actionHelpFingerPrint = QtGui.QAction(MainWindow)
        self.actionHelpFingerPrint.setObjectName("actionHelpFingerPrint")
        self.actionPlot_Legend = QtGui.QAction(MainWindow)
        self.actionPlot_Legend.setObjectName("actionPlot_Legend")
        self.actionFilter_Visible = QtGui.QAction(MainWindow)
        self.actionFilter_Visible.setObjectName("actionFilter_Visible")
        self.actionNormalize_Raw_Data = QtGui.QAction(MainWindow)
        self.actionNormalize_Raw_Data.setObjectName("actionNormalize_Raw_Data")
        self.actionIgnore_Raw_Spectrum = QtGui.QAction(MainWindow)
        self.actionIgnore_Raw_Spectrum.setObjectName("actionIgnore_Raw_Spectrum")
        self.actionInvert_Comparison = QtGui.QAction(MainWindow)
        self.actionInvert_Comparison.setObjectName("actionInvert_Comparison")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit_Program)
        self.menuTools.addAction(self.actionCursor_A)
        self.menuTools.addAction(self.actionCursor_B)
        self.menuTools.addAction(self.actionClear_Cursors)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionLabel_Peak)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCopy_to_Clipboard)
        self.menu_Help.addAction(self.actionRead_Me)
        self.menuOptions.addAction(self.actionPlot_Legend)
        self.menuOptions.addAction(self.actionFilter_Visible)
        self.menuOptions.addAction(self.actionNormalize_Raw_Data)
        self.menuOptions.addAction(self.actionIgnore_Raw_Spectrum)
        self.menuOptions.addAction(self.actionInvert_Comparison)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IMSViewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Spectrum Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Frequency Cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTreeWidget.setSortingEnabled(True)
        self.groupTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "File Info", None, QtGui.QApplication.UnicodeUTF8))
        self.loadWSU_CB.setText(QtGui.QApplication.translate("MainWindow", "Load IMS-TOF?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Filter Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Index:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Index:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "dx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "dy:", None, QtGui.QApplication.UnicodeUTF8))
        self.cursACB.setText(QtGui.QApplication.translate("MainWindow", "Cursor A", None, QtGui.QApplication.UnicodeUTF8))
        self.cursBCB.setText(QtGui.QApplication.translate("MainWindow", "Cursor B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">K<span style=\" vertical-align:sub;\">o</span>:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">K<span style=\" vertical-align:sub;\">o</span>:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.plotLegendCB.setText(QtGui.QApplication.translate("MainWindow", "Plot Legend?", None, QtGui.QApplication.UnicodeUTF8))
        self.invertCompCB.setText(QtGui.QApplication.translate("MainWindow", "Invert Single Comparison?", None, QtGui.QApplication.UnicodeUTF8))
        self.lowPassOn_CB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Needs to be checked for Savtizky-Golay and Low Pass Filter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lowPassOn_CB.setText(QtGui.QApplication.translate("MainWindow", "Filter Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "SG Kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.sgKernel_SB.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Try to set to prime or odd numbers.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "SG Order", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoreRaw_CB.setText(QtGui.QApplication.translate("MainWindow", "Ignore Raw Spectrum if Filtered Data Exist?", None, QtGui.QApplication.UnicodeUTF8))
        self.normRaw_CB.setText(QtGui.QApplication.translate("MainWindow", "Normalize Raw Data?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Drift Cell Length (cm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Pressure (torr):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Temperature (C):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Temperature (C):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Gate Pulse Width (us):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Drift Time (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "IMS Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Toggle Options", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCursor_A.setText(QtGui.QApplication.translate("MainWindow", "Cursor A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCursor_B.setText(QtGui.QApplication.translate("MainWindow", "Cursor B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLabel_Peak.setText(QtGui.QApplication.translate("MainWindow", "Label Peak", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLabel_Peak.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_to_Clipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy Plot to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cursors.setText(QtGui.QApplication.translate("MainWindow", "Clear Cursors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Cursors.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRead_Me.setText(QtGui.QApplication.translate("MainWindow", "Read Me", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPeak_Picking.setText(QtGui.QApplication.translate("MainWindow", "About Peak Picking", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Peaks.setText(QtGui.QApplication.translate("MainWindow", "Find Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_Program.setText(QtGui.QApplication.translate("MainWindow", "Exit Program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpFingerPrint.setText(QtGui.QApplication.translate("MainWindow", "Finger Printing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot_Legend.setText(QtGui.QApplication.translate("MainWindow", "Plot Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilter_Visible.setText(QtGui.QApplication.translate("MainWindow", "Filter Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilter_Visible.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalize_Raw_Data.setText(QtGui.QApplication.translate("MainWindow", "Normalize Raw Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIgnore_Raw_Spectrum.setText(QtGui.QApplication.translate("MainWindow", "Ignore Raw Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert_Comparison.setText(QtGui.QApplication.translate("MainWindow", "Invert Comparison", None, QtGui.QApplication.UnicodeUTF8))

from customTable import CustomTable
from mpl_pyqt4_widget import MPL_Widget
import icons_rc
